# .circleci/config.yml
version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ~/.cache/pip
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Run tests
          command: pytest

  lint:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:  # Всегда устанавливаем зависимости в job lint
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Check code formatting with Black
          command: black --check --diff .

workflows:
  version: 2
  build-test-and-lint:
    jobs:
      - test
      - lint